version: "{build}"
image: Visual Studio 2017
platform: Any CPU
before_build:
 - dotnet restore --packages packages
build_script:
 - dotnet build
test_script:
  - .\packages\opencover\4.7.922\tools\OpenCover.Console.exe