version: "{build}"
image: Visual Studio 2017
platform: Any CPU
before_build:
 - dotnet restore --packages packages
build_script:
 - dotnet build
test_script:
  - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test mbed-cloud-sdk-dotnet\Tests\MbedCloudSDK.UnitTests" -output:"coverage.xml" -oldstyle -filter:"+[MbedCloudSDK*]MbedCloudSDK*"