version: "{build}"
image: Visual Studio 2017
platform: Any CPU
install:
  - "%PYTHON%\\python.exe pip install pip pipenv"
  - pipenv run pip install awscli --three
  - pipenv aws --version

build: off

test_script:
- ps: |
    Invoke-Expression -Command (. venv/bin/activate aws ecr get-login --no-include-email)
    docker pull $env:TESTRUNNER_DOCKER_IMAGE
    docker run --rm --net=host --name=testrunner_container -e "TEST_SERVER_URL=localhost:5000" -e "TEST_FIXTURES_DIR=/home/ubuntu/rpc_fixtures" -v /home/ubuntu/rpc_fixtures:/runner/test_fixtures -v /home/ubuntu/rpc_results:/runner/results ${TESTRUNNER_DOCKER_IMAGE}

after_test:
- ps: |
    echo "tests complete"