version: "{build}"
image: Visual Studio 2017
# install:
#   - choco install awscli
#   - refreshenv

build: off

test_script:
  - ps: git clone -q --branch=master https://$env:GITHUB_TOKEN@github.com/ARMmbed/mbed-cloud-sdk-testrunner.git C:\projects\mbed-cloud-sdk-testrunner
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m pip install --upgrade pip
  - ps: C:\Python36\python.exe -m pip install -r requirements.txt --no-warn-script-location
  - ps: cd ..\mbed-cloud-sdk-dotnet
  - ps: dotnet restore
  - ps: dotnet build -c Debug
  - ps: Start-Job -ScriptBlock { dotnet run --no-restore --no-build -c Debug --project .\Tests\MbedCloudSDK.IntegrationTests\MbedCloudSDK.IntegrationTests.csproj }
  - ps: Start-Sleep -s 15
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m trunner

after_test:
  - ps: echo "tests complete"