version: "{build}"
image: Visual Studio 2017

build: off

test_script:
  - ps: $ErrorActionPreference = 'SilentlyContinue'
  - ps: git clone -q --branch=master https://$env:GITHUB_TOKEN@github.com/ARMmbed/mbed-cloud-sdk-testrunner.git C:\projects\mbed-cloud-sdk-testrunner
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m pip install --upgrade pip
  - ps: C:\Python36\python.exe -m pip install -r requirements.txt --no-warn-script-location
  - ps: cd ..\mbed-cloud-sdk-dotnet
  - ps: dotnet restore --packages packages
  - ps: dotnet build -c Debug
  - ps: .\packages\opencover\4.7.922\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test Tests\MbedCloudSDK.UnitTests --no-restore --no-build" -oldstyle -register:user -filter:"+[MbedCloudSDK*]Mbed* -[MbedCloudSDK.UnitTests*]*" -output:"unit-coverage.xml"
  - ps: Start-Process .\packages\opencover\4.7.922\tools\OpenCover.Console.exe -ArgumentList '-target:"C:\Program Files\dotnet\dotnet.exe"', '-targetargs:"run --no-restore --no-build -c Debug --project .\Tests\MbedCloudSDK.IntegrationTests\MbedCloudSDK.IntegrationTests.csproj"', '-oldstyle', '-register:user', '-filter:"+[MbedCloudSDK*]Mbed* -[MbedCloudSDK.IntegrationTests*]*"', '-output:"int-coverage.xml"'
  - ps: Start-Sleep -s 15
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m trunner
  - ps: Invoke-WebRequest -Uri 'http://localhost:5000/shutdown' -Method 'POST'
  - ps: Start-Sleep -s 15
  - ps: cd ..\mbed-cloud-sdk-dotnet
  - ps: ls
  - ps: $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
  - ps: bash codecov.sh -f "int-coverage.xml"
  - ps: bash codecov.sh -f "unit-coverage.xml"

after_test:
  - ps: echo "tests complete"