version: "{build}"
image: Visual Studio 2017
platform: Any CPU
# install:
#   - choco install awscli
#   - refreshenv

build: off

test_script:
  - ps: git clone -q --branch=master https://$env:GITHUB_TOKEN@github.com/ARMmbed/mbed-cloud-sdk-testrunner.git C:\projects\mbed-cloud-sdk-testrunner
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m pip install --upgrade pip
  - ps: C:\Python36\python.exe -m pip install -r requirements.txt --no-warn-script-location
  - ps: C:\Python36\python.exe -m trunner
  # - ps: dotnet restore
  # - ps: dotnet build
  # - ps: Invoke-Expression -Command (aws ecr get-login --no-include-email)
  # - ps: docker pull $env:TEST_RUNNER_DOCKER_IMAGE
  # - ps: docker run --rm --net=host --name=testrunner_container -e "TEST_SERVER_URL=localhost:5000" -e "TEST_FIXTURES_DIR=/home/ubuntu/rpc_fixtures" -v /home/ubuntu/rpc_fixtures:/runner/test_fixtures -v /home/ubuntu/rpc_results:/runner/results ${TESTRUNNER_DOCKER_IMAGE}

after_test:
  - ps: echo "tests complete"