version: "{build}"
image: Visual Studio 2017

build: off

test_script:
  # python logs are sent to stderr which causes the script to crash. Silently continue on these errors
  - ps: $ErrorActionPreference = 'SilentlyContinue'
  # clone the testrunner
  - ps: git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://$env:GITHUB_TOKEN@github.com/ARMmbed/mbed-cloud-sdk-testrunner.git C:\projects\mbed-cloud-sdk-testrunner;  if (-not $?) { git clone -q --branch=master https://$env:GITHUB_TOKEN@github.com/ARMmbed/mbed-cloud-sdk-testrunner.git C:\projects\mbed-cloud-sdk-testrunner }
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m pip install --upgrade pip
  - ps: C:\Python36\python.exe -m pip install -r requirements.txt --no-warn-script-location
  - ps: cd ..\mbed-cloud-sdk-dotnet
  # packages flag restores packages to packages folder, so we can access the opencover .exe
  - ps: dotnet restore --packages packages
  - ps: dotnet build -c Debug
  # unit tests
  - ps: .\packages\opencover\4.7.922\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test Tests\MbedCloudSDK.UnitTests --no-restore --no-build" -oldstyle -register:user -filter:"+[MbedCloudSDK*]Mbed* -[MbedCloudSDK.UnitTests*]*" -output:"unit-coverage.xml"
  # start a process for the test server
  - ps: Start-Process .\packages\opencover\4.7.922\tools\OpenCover.Console.exe -ArgumentList '-target:"C:\Program Files\dotnet\dotnet.exe"', '-targetargs:"run --no-restore --no-build -c Debug --project .\Tests\MbedCloudSDK.IntegrationTests\MbedCloudSDK.IntegrationTests.csproj"', '-oldstyle', '-register:user', '-filter:"+[MbedCloudSDK*]Mbed* -[MbedCloudSDK.IntegrationTests*]*"', '-output:"int-coverage.xml"'
  # sleep here to ensure server process has time to start
  - ps: Start-Sleep -s 15
  - ps: cd ..\mbed-cloud-sdk-testrunner
  - ps: C:\Python36\python.exe -m trunner
  # we have to manually shut the test_server down so opencover can get coverage
  - ps: Invoke-WebRequest -Uri 'http://localhost:5000/shutdown' -Method 'POST'
  # sleep to make sure test_server process has enough time to stop
  - ps: Start-Sleep -s 15
  - ps: cd ..\mbed-cloud-sdk-dotnet
  - ps: ls
  # upload bith files to codecov
  - ps: $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
  - ps: bash codecov.sh -f "int-coverage.xml"
  - ps: bash codecov.sh -f "unit-coverage.xml"

after_test:
  - ps: echo "tests complete"