sdk_test_server:
    image: test_server_dotnet
    environment:
      - MBED_CLOUD_SDK_HOST
      - MBED_CLOUD_SDK_API_KEY
      - TEST_RUNNER_SHUTDOWN_SERVER=yes
    volumes:
      - ./test_fixtures:/testserver/test_fixtures
testrunner:
    image: 104059736540.dkr.ecr.us-west-2.amazonaws.com/mbed/sdk-testrunner
    environment:
      - TEST_SERVER_URL=http://sdk_test_server:80
      #folder on test server to get test files from
      - TEST_FIXTURES_DIR=/testserver/test_fixtures
    links:
      - sdk_test_server
    volumes:
      - ./integration-results/results:/runner/results
      - ./test_fixtures:/runner/test_fixtures