[AutoVersionConfig]
DEVMODE_TEMPLATE = "{version}-beta{count}"
CONFIG_NAME = "CSHARP"
VERSION_LOCK_VALUE = "true"
VERSION_UNLOCK_VALUE = "false"
RELEASED_VALUE = true
targets = [ "./src/MbedCloudSDK.csproj", "./src/Common/Version.cs" ]

[AutoVersionConfig.key_aliases]
#major = "SDK_MAJOR"
#RELEASE_FIELD = "PRODUCTION"
VersionLock = "VERSION_LOCK"
#COMMIT = "COMMIT"
#COMMIT_COUNT = "COMMIT_COUNT"
Version = "VERSION_KEY"
VersionValue = "VERSION_KEY"
TestrunnerVersion = "TESTRUNNER_VERSION"
#minor = "SDK_MINOR"
#patch = "SDK_PATCH"
